services:
  - type: web
    name: memoryverse-api
    env: docker
    dockerfilePath: Dockerfile
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SECRET_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: REDIS_CACHE_TTL
        sync: false

